name: myip
version: 0.1
summary: Don't know IP? Send it for 5 minutes to USB LED Dream Cheeky
description: This snap shows on the USB LED Dream Cheeky the first 5 minutes of startup what your ip address is.
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel # use "stable" to assert the snap quality

apps:
    myip:
        command: bin/myip
        daemon: simple
        plugs:
          - network-bind
          - network
          - serial-port
    dcled:
        command: dcled

parts:
   dcled:
     plugin: make
     source: https://github.com/kost/dcled.git
     artifacts: [dcled]
     build-packages: [libusb-1.0-0-dev]
   myip:
     plugin: go
     source: src/myip
